name: "josh trommel"
description: "i like cute girls & code"

author: "Josh Trommel"

url: "http://trommel.github.io"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
